include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'
    - '**.config.dart'

  errors:
    invalid_annotation_target: ignore
