name: next_gig
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  i69n: ^2.1.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  intl: ^0.17.0
  clock: ^1.1.1
  auto_route: ^5.0.1
  dio: ^4.0.6
  collection: ^1.16.0
  retrofit: ^3.0.1+1
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.1.5
  just_audio: ^0.9.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  bdd_widget_test: ^1.4.2
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  auto_route_generator: ^5.0.1
  retrofit_generator: ^4.0.1
  mocktail_image_network: ^0.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/deezer_logo.png
    - assets/graphics/main_background.png
    - assets/graphics/splash_background.png
    - assets/json/cities.json
    - assets/json/genres.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700